import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import api from "../../services/api";

function ReportIssue() {
  const navigate = useNavigate(); const [asset, setAsset] = useState(""); const [description, setDescription] = useState(""); const [assets, setAssets] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { api.get("/assets").then((response) => setAssets(response.data?.data || [])).catch((requestError) => setError(requestError.response?.data?.message || "Unable to load assets.")).finally(() => setLoading(false)); }, []);
  async function handleSubmit(event) { event.preventDefault(); if (!asset || !description.trim()) { setError("Select an asset and describe the problem before submitting."); return; } setSaving(true); setError(""); try { await api.post("/maintenance", { assetId: asset, description }); setMessage("Your issue was reported successfully."); setAsset(""); setDescription(""); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to report issue."); } finally { setSaving(false); } }
  return <><div className="page-header"><div><p className="eyebrow">New request</p><h1>Report an Issue</h1><p className="subtitle">Tell us what needs attention and our team will take it from there.</p></div><Link className="button-secondary" to="/student/requests">View my requests</Link></div><section className="form-card"><h2>Issue details</h2><p className="muted">Please provide enough detail for the maintenance team to respond quickly.</p>{error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message} <button className="panel-link" onClick={() => navigate("/student/requests")}>View requests</button></div>}<form onSubmit={handleSubmit}><div className="form-field"><label htmlFor="asset">Select asset</label><select id="asset" className="form-control" value={asset} onChange={(event) => { setAsset(event.target.value); setError(""); }} disabled={loading || assets.length === 0}><option value="">{loading ? "Loading assets..." : assets.length ? "Choose an asset" : "No assets available"}</option>{assets.map((item) => <option key={item._id} value={item._id}>{item.name} · {item.assetCode} · Room {item.room}</option>)}</select></div><div className="form-field"><label htmlFor="description">Issue description</label><textarea id="description" className="form-control" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Describe the damage or problem in detail..." /></div><button className="button-primary" type="submit" disabled={saving || loading || !assets.length}>{saving ? "Submitting..." : "Submit request"}</button></form></section></>;
}
export default ReportIssue;
