import { useNavigate } from "react-router-dom";

export function BuildingMark() { return <div className="brand-mark" aria-hidden="true"><span></span><i></i><b></b></div>; }
export function PasswordField({ id, label, value, onChange, placeholder, visible, onToggle }) { return <div className="auth-field"><label htmlFor={id}>{label}</label><div className="auth-input-wrap"><span className="auth-input-icon" aria-hidden="true">⌁</span><input id={id} type={visible ? "text" : "password"} value={value} onChange={onChange} placeholder={placeholder} minLength="6" required /><button className="password-toggle" type="button" onClick={onToggle} aria-label={visible ? "Hide password" : "Show password"}>{visible ? "Hide" : "Show"}</button></div></div>; }
export default function AuthShell({ mode, children, title, subtitle, error, footer, roleSelector, google, loading }) {
  const navigate = useNavigate(); const signup = mode === "signup";
  // The new route renders in its swapped state with a card entrance animation.
  // Navigate immediately so switching never feels delayed.
  const changeMode = () => navigate(signup ? "/" : "/signup");
  return <main className={`auth-page ${signup ? "is-signup" : "is-login"}`}><div className="auth-orb auth-orb-one"></div><div className="auth-orb auth-orb-two"></div><div className="auth-grid"></div><section className="auth-card" aria-label={signup ? "Create an account" : "Sign in"}><aside className="auth-visual"><div className="visual-copy"><div className="brand-line"><BuildingMark /><span>Hostel Maintenance</span></div><p>Manage. Maintain. Improve.</p></div><div className="illustration" aria-hidden="true"><div className="moon"></div><div className="spark spark-one">✦</div><div className="spark spark-two">✦</div><div className="building"><div className="roof"></div><div className="building-top"><span></span><span></span><span></span></div><div className="building-body"><span></span><span></span><span></span><span></span><span></span><span></span></div><div className="door"></div></div><div className="worker"><div className="head"></div><div className="body"></div><div className="leg leg-one"></div><div className="leg leg-two"></div><div className="wrench">⌕</div></div><div className="ground"></div></div><div className="visual-caption"><strong>Everything in its place.</strong><span>Keep campus living comfortable and connected.</span></div></aside><section className="auth-form-panel"><div className="mobile-brand"><BuildingMark /><span>Hostel Maintenance</span></div><div className="auth-heading"><p className="eyebrow">{signup ? "GET STARTED" : "WELCOME BACK"}</p><h1>{title}</h1><p>{subtitle}</p></div>{roleSelector}<div className="auth-form-content">{children}</div>{error && <p className="auth-error" role="alert">{error}</p>}{google}{loading && <p className="auth-status">Signing you in with Google…</p>}<p className="auth-footer">{footer} <button type="button" onClick={changeMode}>{signup ? "Sign in" : "Create account"}</button></p><p className="auth-credit">Web created by Aman & Dilip</p></section></section></main>;
}
