import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import StatusBadge from "../../components/StatusBadge";
import api from "../../services/api";

function RequestDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [request, setRequest] = useState(null); const [status, setStatus] = useState(""); const [resolutionNote, setResolutionNote] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { api.get(`/maintenance/${id}`).then((response) => { const data = response.data?.data || response.data; setRequest(data); setStatus(data.status); setResolutionNote(data.resolutionNote || ""); }).catch((requestError) => setError(requestError.response?.data?.message || "Unable to load request details.")).finally(() => setLoading(false)); }, [id]);
  async function handleUpdate(event) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const response = await api.put(`/maintenance/${id}`, { status, resolutionNote }); const data = response.data?.data || response.data; setRequest(data); setMessage("Request updated successfully."); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to update request."); } finally { setSaving(false); } }
  if (loading) return <div className="loading-state">Loading request details...</div>;
  if (!request) return <div className="empty-state">Request not found.</div>;
  return <><div className="page-header"><div><p className="eyebrow">Request details</p><h1>Maintenance request</h1><p className="subtitle">Submitted {new Date(request.createdAt).toLocaleDateString(undefined, { day: "numeric", month: "long", year: "numeric" })}</p></div><button className="button-secondary" onClick={() => navigate("/admin/requests")}>Back to requests</button></div>{error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message}</div>}<div className="detail-layout"><section className="panel"><div className="panel-heading"><h2>Request information</h2><StatusBadge status={request.status} /></div><dl className="detail-list"><div><dt>Student</dt><dd>{request.reportedBy?.name || "Unknown"}</dd></div><div><dt>Email</dt><dd>{request.reportedBy?.email || "Not available"}</dd></div><div><dt>Asset</dt><dd>{request.assetId?.name || "Unknown asset"}</dd></div><div><dt>Asset code</dt><dd>{request.assetId?.assetCode || "Not available"}</dd></div><div><dt>Hostel</dt><dd>{request.assetId?.hostel || "Not available"}</dd></div><div><dt>Room</dt><dd>{request.assetId?.room || "Not available"}</dd></div></dl><div className="description-box"><strong>Issue description</strong><p>{request.description}</p></div></section><section className="panel"><div className="panel-heading"><h2>Update request</h2></div><form onSubmit={handleUpdate}><div className="form-field"><label htmlFor="status">Current status</label><select id="status" className="form-control" value={status} onChange={(event) => setStatus(event.target.value)}><option>Pending</option><option>In Process</option><option>Resolved</option><option>Rejected</option></select></div><div className="form-field"><label htmlFor="resolution">Resolution note</label><textarea id="resolution" className="form-control" value={resolutionNote} onChange={(event) => setResolutionNote(event.target.value)} placeholder="Add context for the student..." /></div><button className="button-primary" type="submit" disabled={saving}>{saving ? "Saving..." : "Save changes"}</button></form></section></div></>;
}
export default RequestDetails;
